### ISSUE TITLE
Session Formatting

### ISSUE THREAD

**Issue by deysonali** [aquanauts/terrain#19]
- Session History URL List, highlight error occurrences
- Error stack trace - fixed width font https://getbootstrap.com/docs/4.0/content/code/

**Comment by deysonali** [comment]
- Show difference between hash change and reload

**Comment by deysonali** [comment]
- Add time of reload/hash change

**Comment by benrady-aq** [comment]
Show each line of the stack trace on a separate line

**Comment by benrady-aq** [comment]
Format 'Error Event Message' and 'Error Message' columns in fixed width font

**Comment by deysonali** [comment]
- Consider feature that collapses rows without errors
- Refactor the code with renderer functions
- Add hyperlinks to linkable items
- Be able to show multiple errors for the same sessionHistory entry
